### ISSUE TITLE
ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@3d4eac69-org.sonar.server.plugins.ServerPluginManager': Initialization of bean failed; nested exception is java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonar-swift-plugin-1.6.1.jar

### ISSUE THREAD

**Issue by readonlyuser1** [sonar-next/sonar-swift#23]
### New Issue Checklist

- [x] Updated the plugin to the latest version 
- [x] I read the [Contribution Guidelines](https://github.com/tal-tech/sonar-swift/blob/master/CONTRIBUTING.md)
- [x] I read the [documentation](https://github.com/tal-tech/sonar-swift/wiki)
- [x] I searched for existing [GitHub issues](https://github.com/tal-tech/sonar-swift/issues)

### Issue Description
sonarqube update to https://github.com/SonarSource/sonarqube/releases/tag/9.4.0.54424
https://github.com/sonar-next

[sonar-swift](https://github.com/sonar-next/sonar-swift) update to https://github.com/sonar-next/sonar-swift/releases/tag/v1.6.1

##### Command executed

sudo chown -R sonaruser:sonaruser /opt/sonarqube
sudo chmod 777 /opt/sonarqube/extensions/plugins/sonar-swift-plugin-1.6.1.jar
systemctl daemon-reload && sudo service sonarqube stop && sudo service sonarqube start && sudo systemctl status sonarqube

`==> /opt/sonarqube/logs/es.log <==
2022.04.04 19:30:32 INFO  es[][o.e.t.NettyAllocator] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=256kb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=1mb, heap_size=512mb}]
2022.04.04 19:30:32 INFO  es[][o.e.i.r.RecoverySettings] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
2022.04.04 19:30:32 INFO  es[][o.e.d.DiscoveryModule] using discovery type [zen] and seed hosts providers [settings]
2022.04.04 19:30:32 INFO  es[][o.e.g.DanglingIndicesState] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
2022.04.04 19:30:32 INFO  es[][o.e.n.Node] initialized
2022.04.04 19:30:32 INFO  es[][o.e.n.Node] starting ...
2022.04.04 19:30:32 INFO  es[][o.e.t.TransportService] publish_address {127.0.0.1:37333}, bound_addresses {127.0.0.1:37333}
2022.04.04 19:30:33 INFO  es[][o.e.b.BootstrapChecks] explicitly enforcing bootstrap checks
2022.04.04 19:30:33 INFO  es[][o.e.c.c.Coordinator] cluster UUID [5QN3LZMpTne4vkHYqHNOIQ]
2022.04.04 19:30:33 INFO  es[][o.e.c.s.MasterService] elected-as-master ([1] nodes joined)[{sonarqube}{Nc76oY_SRLm5lbvh6skzhQ}{13GSlQInQqW0aPlEw-QMJw}{127.0.0.1}{127.0.0.1:37333}{cdfhimrsw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 25, version: 250, delta: master node changed {previous [], current [{sonarqube}{Nc76oY_SRLm5lbvh6skzhQ}{13GSlQInQqW0aPlEw-QMJw}{127.0.0.1}{127.0.0.1:37333}{cdfhimrsw}]}
2022.04.04 19:30:33 INFO  es[][o.e.c.s.ClusterApplierService] master node changed {previous [], current [{sonarqube}{Nc76oY_SRLm5lbvh6skzhQ}{13GSlQInQqW0aPlEw-QMJw}{127.0.0.1}{127.0.0.1:37333}{cdfhimrsw}]}, term: 25, version: 250, reason: Publication{term=25, version=250}
2022.04.04 19:30:33 INFO  es[][o.e.h.AbstractHttpServerTransport] publish_address {127.0.0.1:9001}, bound_addresses {127.0.0.1:9001}
2022.04.04 19:30:33 INFO  es[][o.e.n.Node] started
2022.04.04 19:30:33 INFO  es[][o.e.g.GatewayService] recovered [7] indices into cluster_state
2022.04.04 19:30:36 INFO  es[][o.e.c.r.a.AllocationService] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[components][4], [components][3], [components][0]]]).

==> /opt/sonarqube/logs/sonar.20220404.log <==
2022.04.04 19:30:36 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2022.04.04 19:30:36 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[WEB_SERVER] from [/opt/sonarqube]: /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -Dcom.redhat.fips=false -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -server -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=web -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-9.4.0.54424.jar:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.3.3.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process4299437899819753834properties
19:30:36.417 [main] INFO com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Loading agent
19:30:36.436 [main] DEBUG com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Transforming class org.sonar.server.almsettings.MultipleAlmFeatureProvider
19:30:36.521 [main] DEBUG com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Transforming class org.sonar.server.newcodeperiod.ws.SetAction
19:30:36.540 [main] DEBUG com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Transforming class org.sonar.server.newcodeperiod.ws.UnsetAction

==> /opt/sonarqube/logs/web.log <==
2022.04.04 19:30:36 INFO  web[][o.s.p.ProcessEntryPoint] Starting Web Server
2022.04.04 19:30:37 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2022.04.04 19:30:37 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 9.4.0.54424 / 5c36a2e19337da136080a276102eaaefce073c68
2022.04.04 19:30:37 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://localhost/sonardb
2022.04.04 19:30:38 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
2022.04.04 19:30:38 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2022.04.04 19:30:39 INFO  web[][o.s.c.e.CoreExtensionsLoader] Loaded core extensions: Community Branch Plugin
2022.04.04 19:30:39 WARN  web[][o.s.c.a.AnnotationConfigApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@3d4eac69-org.sonar.server.plugins.ServerPluginManager': Initialization of bean failed; nested exception is java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonar-swift-plugin-1.6.1.jar
2022.04.04 19:30:39 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@3d4eac69-org.sonar.server.plugins.ServerPluginManager': Initialization of bean failed; nested exception is java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonar-swift-plugin-1.6.1.jar
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:187)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:80)
        at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:105)
        at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:196)
        at org.sonar.server.platform.PlatformImpl.startLevel2Container(PlatformImpl.java:169)
        at org.sonar.server.platform.PlatformImpl.init(PlatformImpl.java:77)
        at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4763)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5232)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonar-swift-plugin-1.6.1.jar
        at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:125)
        at org.sonar.server.plugins.ServerPluginInfo.create(ServerPluginInfo.java:37)
        at org.sonar.server.plugins.PluginJarLoader.lambda$getExternalPluginsMetadata$5(PluginJarLoader.java:203)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.sonar.server.plugins.PluginJarLoader.loadPluginsFromDir(PluginJarLoader.java:233)
        at org.sonar.server.plugins.PluginJarLoader.getExternalPluginsMetadata(PluginJarLoader.java:203)
        at org.sonar.server.plugins.PluginJarLoader.loadPlugins(PluginJarLoader.java:94)
        at org.sonar.server.plugins.ServerPluginManager.start(ServerPluginManager.java:64)
        at org.sonar.core.platform.StartableBeanPostProcessor.postProcessBeforeInitialization(StartableBeanPostProcessor.java:33)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        ... 24 common frames omitted
Caused by: java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:321)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:287)
        at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:120)
        ... 41 common frames omitted
2022.04.04 19:30:39 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2022.04.04 19:30:39 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process

==> /opt/sonarqube/logs/es.log <==
2022.04.04 19:30:39 INFO  es[][o.e.n.Node] stopping ...

==> /opt/sonarqube/logs/sonar.20220404.log <==
2022.04.04 19:30:39 INFO  app[][o.s.a.SchedulerImpl] Process[Web Server] is stopped

==> /opt/sonarqube/logs/es.log <==
2022.04.04 19:30:39 INFO  es[][o.e.n.Node] stopped
2022.04.04 19:30:39 INFO  es[][o.e.n.Node] closing ...
2022.04.04 19:30:39 INFO  es[][o.e.n.Node] closed

==> /opt/sonarqube/logs/sonar.20220404.log <==
2022.04.04 19:30:39 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 143
2022.04.04 19:30:39 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
2022.04.04 19:30:39 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
<-- Wrapper Stopped
--> Wrapper Started as Daemon
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
`

**Comment by magaofei** [comment]
Not support SonarQube 9.4 version, Please wait.

**Comment by magaofei** [comment]
Please update the latest version of the plugin.
